import unittest

import dnbpy


class TestVectorIndexToCoords(unittest.TestCase):

    def test_convert_vector_index_to_coordinates_1x1(self):
        game = dnbpy.Game((1, 1), ['player1', 'player2'])
        coordinates = game.convert_vector_index_to_coordinates(0)
        self.assertEqual(coordinates, (0, 1))
        coordinates = game.convert_vector_index_to_coordinates(1)
        self.assertEqual(coordinates, (1, 0))
        coordinates = game.convert_vector_index_to_coordinates(2)
        self.assertEqual(coordinates, (1, 2))
        coordinates = game.convert_vector_index_to_coordinates(3)
        self.assertEqual(coordinates, (2, 1))

    def test_convert_vector_index_to_coordinates_1x2(self):
        game = dnbpy.Game((1, 2), ['player1', 'player2'])
        coordinates = game.convert_vector_index_to_coordinates(0)
        self.assertEqual(coordinates, (0, 1))
        coordinates = game.convert_vector_index_to_coordinates(1)
        self.assertEqual(coordinates, (0, 3))
        coordinates = game.convert_vector_index_to_coordinates(2)
        self.assertEqual(coordinates, (1, 0))
        coordinates = game.convert_vector_index_to_coordinates(3)
        self.assertEqual(coordinates, (1, 2))
        coordinates = game.convert_vector_index_to_coordinates(4)
        self.assertEqual(coordinates, (1, 4))
        coordinates = game.convert_vector_index_to_coordinates(5)
        self.assertEqual(coordinates, (2, 1))
        coordinates = game.convert_vector_index_to_coordinates(6)
        self.assertEqual(coordinates, (2, 3))

    def test_convert_vector_index_to_coordinates_2x1(self):
        game = dnbpy.Game((2, 1), ['player1', 'player2'])
        coordinates = game.convert_vector_index_to_coordinates(0)
        self.assertEqual(coordinates, (0, 1))
        coordinates = game.convert_vector_index_to_coordinates(1)
        self.assertEqual(coordinates, (1, 0))
        coordinates = game.convert_vector_index_to_coordinates(2)
        self.assertEqual(coordinates, (1, 2))
        coordinates = game.convert_vector_index_to_coordinates(3)
        self.assertEqual(coordinates, (2, 1))
        coordinates = game.convert_vector_index_to_coordinates(4)
        self.assertEqual(coordinates, (3, 0))
        coordinates = game.convert_vector_index_to_coordinates(5)
        self.assertEqual(coordinates, (3, 2))
        coordinates = game.convert_vector_index_to_coordinates(6)
        self.assertEqual(coordinates, (4, 1))

    def test_convert_vector_index_to_coordinates_2x2(self):
        game = dnbpy.Game((2, 2), ['player1', 'player2'])
        coordinates = game.convert_vector_index_to_coordinates(0)
        self.assertEqual(coordinates, (0, 1))
        coordinates = game.convert_vector_index_to_coordinates(1)
        self.assertEqual(coordinates, (0, 3))
        coordinates = game.convert_vector_index_to_coordinates(2)
        self.assertEqual(coordinates, (1, 0))
        coordinates = game.convert_vector_index_to_coordinates(3)
        self.assertEqual(coordinates, (1, 2))
        coordinates = game.convert_vector_index_to_coordinates(4)
        self.assertEqual(coordinates, (1, 4))
        coordinates = game.convert_vector_index_to_coordinates(5)
        self.assertEqual(coordinates, (2, 1))
        coordinates = game.convert_vector_index_to_coordinates(6)
        self.assertEqual(coordinates, (2, 3))
        coordinates = game.convert_vector_index_to_coordinates(7)
        self.assertEqual(coordinates, (3, 0))
        coordinates = game.convert_vector_index_to_coordinates(8)
        self.assertEqual(coordinates, (3, 2))
        coordinates = game.convert_vector_index_to_coordinates(9)
        self.assertEqual(coordinates, (3, 4))
        coordinates = game.convert_vector_index_to_coordinates(10)
        self.assertEqual(coordinates, (4, 1))
        coordinates = game.convert_vector_index_to_coordinates(11)
        self.assertEqual(coordinates, (4, 3))

    def test_convert_vector_index_to_coordinates_3x3(self):
        game = dnbpy.Game((3, 3), ['player1', 'player2'])
        coordinates = game.convert_vector_index_to_coordinates(0)
        self.assertEqual(coordinates, (0, 1))
        coordinates = game.convert_vector_index_to_coordinates(1)
        self.assertEqual(coordinates, (0, 3))
        coordinates = game.convert_vector_index_to_coordinates(2)
        self.assertEqual(coordinates, (0, 5))
        coordinates = game.convert_vector_index_to_coordinates(3)
        self.assertEqual(coordinates, (1, 0))
        coordinates = game.convert_vector_index_to_coordinates(4)
        self.assertEqual(coordinates, (1, 2))
        coordinates = game.convert_vector_index_to_coordinates(5)
        self.assertEqual(coordinates, (1, 4))
        coordinates = game.convert_vector_index_to_coordinates(6)
        self.assertEqual(coordinates, (1, 6))
        coordinates = game.convert_vector_index_to_coordinates(7)
        self.assertEqual(coordinates, (2, 1))
        coordinates = game.convert_vector_index_to_coordinates(8)
        self.assertEqual(coordinates, (2, 3))
        coordinates = game.convert_vector_index_to_coordinates(9)
        self.assertEqual(coordinates, (2, 5))
        coordinates = game.convert_vector_index_to_coordinates(10)
        self.assertEqual(coordinates, (3, 0))
        coordinates = game.convert_vector_index_to_coordinates(11)
        self.assertEqual(coordinates, (3, 2))
        coordinates = game.convert_vector_index_to_coordinates(12)
        self.assertEqual(coordinates, (3, 4))
        coordinates = game.convert_vector_index_to_coordinates(13)
        self.assertEqual(coordinates, (3, 6))
        coordinates = game.convert_vector_index_to_coordinates(14)
        self.assertEqual(coordinates, (4, 1))
        coordinates = game.convert_vector_index_to_coordinates(15)
        self.assertEqual(coordinates, (4, 3))
        coordinates = game.convert_vector_index_to_coordinates(16)
        self.assertEqual(coordinates, (4, 5))
        coordinates = game.convert_vector_index_to_coordinates(17)
        self.assertEqual(coordinates, (5, 0))
        coordinates = game.convert_vector_index_to_coordinates(18)
        self.assertEqual(coordinates, (5, 2))
        coordinates = game.convert_vector_index_to_coordinates(19)
        self.assertEqual(coordinates, (5, 4))
        coordinates = game.convert_vector_index_to_coordinates(20)
        self.assertEqual(coordinates, (5, 6))
        coordinates = game.convert_vector_index_to_coordinates(21)
        self.assertEqual(coordinates, (6, 1))
        coordinates = game.convert_vector_index_to_coordinates(22)
        self.assertEqual(coordinates, (6, 3))
        coordinates = game.convert_vector_index_to_coordinates(23)
        self.assertEqual(coordinates, (6, 5))
