import unittest

import dnbpy


class TestVectorIndexToCoords(unittest.TestCase):

    def test_convert_vector_index_to_coordinates_1x1(self):
        coordinates = dnbpy.convert_vector_index_to_coordinates((1, 1), 0)
        self.assertEqual(coordinates, (0, 1))
        coordinates = dnbpy.convert_vector_index_to_coordinates((1, 1), 1)
        self.assertEqual(coordinates, (1, 0))
        coordinates = dnbpy.convert_vector_index_to_coordinates((1, 1), 2)
        self.assertEqual(coordinates, (1, 2))
        coordinates = dnbpy.convert_vector_index_to_coordinates((1, 1), 3)
        self.assertEqual(coordinates, (2, 1))

    def test_convert_vector_index_to_coordinates_1x2(self):
        coordinates = dnbpy.convert_vector_index_to_coordinates((1, 2), 0)
        self.assertEqual(coordinates, (0, 1))
        coordinates = dnbpy.convert_vector_index_to_coordinates((1, 2), 1)
        self.assertEqual(coordinates, (0, 3))
        coordinates = dnbpy.convert_vector_index_to_coordinates((1, 2), 2)
        self.assertEqual(coordinates, (1, 0))
        coordinates = dnbpy.convert_vector_index_to_coordinates((1, 2), 3)
        self.assertEqual(coordinates, (1, 2))
        coordinates = dnbpy.convert_vector_index_to_coordinates((1, 2), 4)
        self.assertEqual(coordinates, (1, 4))
        coordinates = dnbpy.convert_vector_index_to_coordinates((1, 2), 5)
        self.assertEqual(coordinates, (2, 1))
        coordinates = dnbpy.convert_vector_index_to_coordinates((1, 2), 6)
        self.assertEqual(coordinates, (2, 3))

    def test_convert_vector_index_to_coordinates_2x1(self):
        coordinates = dnbpy.convert_vector_index_to_coordinates((2, 1), 0)
        self.assertEqual(coordinates, (0, 1))
        coordinates = dnbpy.convert_vector_index_to_coordinates((2, 1), 1)
        self.assertEqual(coordinates, (1, 0))
        coordinates = dnbpy.convert_vector_index_to_coordinates((2, 1), 2)
        self.assertEqual(coordinates, (1, 2))
        coordinates = dnbpy.convert_vector_index_to_coordinates((2, 1), 3)
        self.assertEqual(coordinates, (2, 1))
        coordinates = dnbpy.convert_vector_index_to_coordinates((2, 1), 4)
        self.assertEqual(coordinates, (3, 0))
        coordinates = dnbpy.convert_vector_index_to_coordinates((2, 1), 5)
        self.assertEqual(coordinates, (3, 2))
        coordinates = dnbpy.convert_vector_index_to_coordinates((2, 1), 6)
        self.assertEqual(coordinates, (4, 1))

    def test_convert_vector_index_to_coordinates_2x2(self):
        coordinates = dnbpy.convert_vector_index_to_coordinates((2, 2), 0)
        self.assertEqual(coordinates, (0, 1))
        coordinates = dnbpy.convert_vector_index_to_coordinates((2, 2), 1)
        self.assertEqual(coordinates, (0, 3))
        coordinates = dnbpy.convert_vector_index_to_coordinates((2, 2), 2)
        self.assertEqual(coordinates, (1, 0))
        coordinates = dnbpy.convert_vector_index_to_coordinates((2, 2), 3)
        self.assertEqual(coordinates, (1, 2))
        coordinates = dnbpy.convert_vector_index_to_coordinates((2, 2), 4)
        self.assertEqual(coordinates, (1, 4))
        coordinates = dnbpy.convert_vector_index_to_coordinates((2, 2), 5)
        self.assertEqual(coordinates, (2, 1))
        coordinates = dnbpy.convert_vector_index_to_coordinates((2, 2), 6)
        self.assertEqual(coordinates, (2, 3))
        coordinates = dnbpy.convert_vector_index_to_coordinates((2, 2), 7)
        self.assertEqual(coordinates, (3, 0))
        coordinates = dnbpy.convert_vector_index_to_coordinates((2, 2), 8)
        self.assertEqual(coordinates, (3, 2))
        coordinates = dnbpy.convert_vector_index_to_coordinates((2, 2), 9)
        self.assertEqual(coordinates, (3, 4))
        coordinates = dnbpy.convert_vector_index_to_coordinates((2, 2), 10)
        self.assertEqual(coordinates, (4, 1))
        coordinates = dnbpy.convert_vector_index_to_coordinates((2, 2), 11)
        self.assertEqual(coordinates, (4, 3))

    def test_convert_vector_index_to_coordinates_3x3(self):
        coordinates = dnbpy.convert_vector_index_to_coordinates((3, 3), 0)
        self.assertEqual(coordinates, (0, 1))
        coordinates = dnbpy.convert_vector_index_to_coordinates((3, 3), 1)
        self.assertEqual(coordinates, (0, 3))
        coordinates = dnbpy.convert_vector_index_to_coordinates((3, 3), 2)
        self.assertEqual(coordinates, (0, 5))
        coordinates = dnbpy.convert_vector_index_to_coordinates((3, 3), 3)
        self.assertEqual(coordinates, (1, 0))
        coordinates = dnbpy.convert_vector_index_to_coordinates((3, 3), 4)
        self.assertEqual(coordinates, (1, 2))
        coordinates = dnbpy.convert_vector_index_to_coordinates((3, 3), 5)
        self.assertEqual(coordinates, (1, 4))
        coordinates = dnbpy.convert_vector_index_to_coordinates((3, 3), 6)
        self.assertEqual(coordinates, (1, 6))
        coordinates = dnbpy.convert_vector_index_to_coordinates((3, 3), 7)
        self.assertEqual(coordinates, (2, 1))
        coordinates = dnbpy.convert_vector_index_to_coordinates((3, 3), 8)
        self.assertEqual(coordinates, (2, 3))
        coordinates = dnbpy.convert_vector_index_to_coordinates((3, 3), 9)
        self.assertEqual(coordinates, (2, 5))
        coordinates = dnbpy.convert_vector_index_to_coordinates((3, 3), 10)
        self.assertEqual(coordinates, (3, 0))
        coordinates = dnbpy.convert_vector_index_to_coordinates((3, 3), 11)
        self.assertEqual(coordinates, (3, 2))
        coordinates = dnbpy.convert_vector_index_to_coordinates((3, 3), 12)
        self.assertEqual(coordinates, (3, 4))
        coordinates = dnbpy.convert_vector_index_to_coordinates((3, 3), 13)
        self.assertEqual(coordinates, (3, 6))
        coordinates = dnbpy.convert_vector_index_to_coordinates((3, 3), 14)
        self.assertEqual(coordinates, (4, 1))
        coordinates = dnbpy.convert_vector_index_to_coordinates((3, 3), 15)
        self.assertEqual(coordinates, (4, 3))
        coordinates = dnbpy.convert_vector_index_to_coordinates((3, 3), 16)
        self.assertEqual(coordinates, (4, 5))
        coordinates = dnbpy.convert_vector_index_to_coordinates((3, 3), 17)
        self.assertEqual(coordinates, (5, 0))
        coordinates = dnbpy.convert_vector_index_to_coordinates((3, 3), 18)
        self.assertEqual(coordinates, (5, 2))
        coordinates = dnbpy.convert_vector_index_to_coordinates((3, 3), 19)
        self.assertEqual(coordinates, (5, 4))
        coordinates = dnbpy.convert_vector_index_to_coordinates((3, 3), 20)
        self.assertEqual(coordinates, (5, 6))
        coordinates = dnbpy.convert_vector_index_to_coordinates((3, 3), 21)
        self.assertEqual(coordinates, (6, 1))
        coordinates = dnbpy.convert_vector_index_to_coordinates((3, 3), 22)
        self.assertEqual(coordinates, (6, 3))
        coordinates = dnbpy.convert_vector_index_to_coordinates((3, 3), 23)
        self.assertEqual(coordinates, (6, 5))
